### PR TITLE
Fixes cyrillic glyphs localized for Macedonian

### PR DESCRIPTION
**Pull request by dimztimz**
Resolved the most critical error in Cyrillic localized shapes for Macedonian and Serbian. See issue #10

### CODE REVIEW

**Comment by vishalvijayraghavan** [comment]
Hi dimztimz,
Thanks for the PR, can you please send some description about that PR because I am unable to understand changes.

**Comment by dimztimz** [comment]
Please see the linked issue #10 and see each commit one by one.

**Comment by dimztimz** [comment]
Did you managed to understand the changes?

**Comment by vishalvijayraghavan** [comment]
Your [commits](https://github.com/liberationfonts/liberation-fonts/commits/devel) have been merged.
Hence closing this PR.
Thanks

**Pull request closed without merging**
